### ISSUE TITLE
Image docker : interface inaccessible

### ISSUE THREAD

**Issue by mimo38** [jperon/musite#1]
- Je fonctionne sous Mac
- Docker est installé
- Kitematic est installé
- l'image [https://hub.docker.com/r/musite/musite/](https://hub.docker.com/r/musite/musite/) "pullée"

--> dans Kitematic le "web preview" renvoie au navigateur (http://localhost:32769/) mais  "La connexion a échoué" ou "La page localhost ne fonctionne pas, localhost n'a envoyé aucune donnée." selon les navigateurs.

HELP!

**Comment by jperon** [comment]
- Avez-vous un pare-feu installé sur votre ordinateur ?
- Avez-vous bien associé les différents "volumes" à des dossiers de votre système ?

**Comment by mimo38** [comment]
Non, actuellement j'arrive à ce message d'erreur
Error checking TLS connection: Something went wrong running an SSH command!

```
                    ##         .
              ## ## ##        ==
           ## ## ## ## ##    ===
       /"""""""""""""""""\___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
       \______ o           __/
         \    \         __/
          \____\_______/
```

Error getting IP address: Something went wrong running an SSH command!

**Comment by mimo38** [comment]
> docker ps

retourne

CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                   NAMES
caf540466d14        musite/musite:latest   "/opt/musite/serveur."   55 seconds ago      Up 50 seconds       0.0.0.0:32772->80/tcp   musite-2

**Comment by jperon** [comment]
Ce dernier message est normal, autant que je sache. Pourriez-vous : 
- réessayer d'accéder à l'interface ;
- si ça ne fonctionne toujours pas, essayer de faire fonctionner une autre image docker (par exemple https://hub.docker.com/_/nginx/) ; si celle-ci ne marche pas, c'est que le problème relève de docker, et je ne suis pas assez compétent pour le résoudre… De mon côté, je n'ai jamais rencontré ce problème.

**Comment by mimo38** [comment]
Nouvelle erreur :
J'ai tout effacé, tout re-téléchargé
"hello-world" me re-dirige vers l'interface graphique

mais "musite" non. Le "container logs" me dit :

> /usr/lib/python3/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
>   warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

Y-a-til d'autres contrôles à faire ?

**Comment by jperon** [comment]
Peut-être ai-je trouvé la cause du problème. Pourriez-vous essayer, s'il vous plaît, de supprimer musite de Kitematic, puis d'effacer le contenu des dossiers correspondant aux volumes de musite, et enfin re-télécharger musite dans Kitematic ? Je pense que f77aadf devrait corriger le défaut.

**Comment by mimo38** [comment]
> Pourriez-vous essayer, s'il vous plaît, de supprimer musite de Kitematic, puis d'effacer le contenu des dossiers correspondant aux volumes de musite, et enfin re-télécharger musite dans Kitematic ?

Opération effectuée, problème résolu ! :smile:
Merci jperon !

**Comment by jperon** [comment]
Merci à vous pour le signalement d'erreur.
