### ISSUE TITLE
Rafraîchissement

### ISSUE THREAD

**Issue by mimo38** [jperon/musite#2]
L'affichage de l'aperçu des documents ne correspond pas au fichier compilé, mais à une ancienne version qui ne prend pas en compte les dernières modification.
Autrement dit, le pdf qui s'affiche dans le navigateur est différent de celui qui se trouve dans le fichier *static/docs/pdf*

**Comment by jperon** [comment]
En effet… En attendant que je trouve le moyen de corriger cela, vous pouvez
sous firefox faire un clic droit, Ce cadre>Actualiser le cadre.

**Comment by jperon** [comment]
*A priori*, la dernière version devrait régler ce problème ; je vous laisse vérifier avant de fermer cette *issue*.
Merci beaucoup !

**Comment by jperon** [comment]
Le problème n'était pas corrigé, mais il l'est maintenant avec la dernière modification. Si cela ne fonctionnait pas chez vous, n'hésitez pas à rouvrir l'*issue*.
