### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mimo38** [jperon/musite#3]
Il manque un bouton vers la liste de **projet*s*** (*http://localhost:32769/fr/_projets*) quand on travaille dans un projet. On peut juste retourner à la racine du projet en cours  (ex : *http://localhost:32769/fr/musite-doc*).
Ne serait-il pas judicieux de faire cet ajout ?

**Comment by jperon** [comment]
Pourriez-vous, s'il vous plaît, tester la dernière version et me dire si cela vous va ?

**Comment by mimo38** [comment]
J'ai exécuté docker pull musite/musite
mais je n'ai pas la même version que sur [musite.dtdns.net](https://musite.dtdns.net) avec le chemin d'accès en haut.
Mais c'est exactement ce que j'attendais, merci bien.

**Comment by mimo38** [comment]
Je viens de supprimer le dernier commentaire, car c'est bon, ça marche!
Excellent, merci beaucoup!
