### ISSUE TITLE
Site indisponible

### ISSUE THREAD

**Issue by mimo38** [jperon/musite#6]
Le site [ici](https://musite.jprn.tk) renvoie une erreur (inaccessible me dit *Opera*)

**Comment by jperon** [comment]
Avez-vous toujours cette erreur ? Ici avec Firefox, ça fonctionne sans difficulté.

**Comment by mimo38** [comment]
Cela fonctionne avec un Android. J'essaierai plus tard avec *Opera*

**Comment by mimo38** [comment]
Après essai, cela ne fonctionne avec aucun navigateur "classique" :

> Ce site est inaccessible
Impossible de trouver l'adresse IP du serveur de musite.jprn.tk.
DNS_PROBE_FINISHED_NXDOMAIN

il faut passer par Tor… Bloquage du FAI ?

**Comment by mimo38** [comment]
Je viens de changer l'adresse du serveur DNS (sans savoir ce que je faisais), et ça passe ! Vive l'informatique
